
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build:       # This job runs in the build stage, which runs first.
  image: docker:latest
  services:
   - docker:dind
  stage: build
  script:
    - echo "Compiling the code..."
    - docker build -t api .
    - echo "Compile complete."

deploy-to-prod:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - docker rm -f server
    - docker run -d --name=server -p 5000:5000 api
    - echo "Application successfully deployed."
